apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-service
  template:
    metadata:
      labels:
        app: weather-service
    spec:
      containers:
      - name: weather-service
        image: weather-service:latest
        imagePullPolicy: Never  # ← ADDED
        ports:
        - containerPort: 5001
        env:
        - name: WEATHER_API_KEY
          # value: "c1e5437f731b74d1a78ab5e73e2cfc28"
          valueFrom:
            secretKeyRef:
              name: weather-api-key
              key: WEATHER_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  selector:
    app: weather-service
  ports:
  - port: 5001
    targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: outfit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outfit-service
  template:
    metadata:
      labels:
        app: outfit-service
    spec:
      containers:
      - name: outfit-service
        image: outfit-service:latest
        imagePullPolicy: Never  # ← ADDED
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: outfit-service
spec:
  selector:
    app: outfit-service
  ports:
  - port: 5002
    targetPort: 5002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wardrobe-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wardrobe-service
  template:
    metadata:
      labels:
        app: wardrobe-service
    spec:
      containers:
      - name: wardrobe-service
        image: wardrobe-service:latest
        imagePullPolicy: Never  # ← ADDED
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: wardrobe-service
spec:
  selector:
    app: wardrobe-service
  ports:
  - port: 5003
    targetPort: 5003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway:latest
        imagePullPolicy: Never  # ← ADDED
        ports:
        - containerPort: 8000
        env:
        - name: WEATHER_SERVICE
          value: "http://weather-service:5001"
        - name: OUTFIT_SERVICE
          value: "http://outfit-service:5002"
        - name: WARDROBE_SERVICE
          value: "http://wardrobe-service:5003"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        imagePullPolicy: Never  # ← ADDED
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_BASE_URL
          value: "/api"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000